defmodule Viva.Avatars.Systems.SocialBrain do
  @moduledoc """
  The Social Brain Engine.
  Calculates the metabolic cost of hypocrisy (Social Mask) and makes strategic social decisions.

  Key Concepts:
  - **Hypocrisy Cost:** The stress (cortisol) generated by the divergence between internal feelings and external expression.
  - **Social Strategy:** Deciding when to lie based on Moral Flexibility and Social Ambition.
  """

  alias Viva.Avatars.Avatar

  @doc """
  Calculates the physiological cost of maintaining a social mask.
  Returns the amount of Cortisol (stress) to be added to the BioState.
  """
  @spec calculate_mask_stress(Avatar.t(), float()) :: float()
  def calculate_mask_stress(%Avatar{} = avatar, mask_intensity) do
    # Base stress is proportional to mask intensity
    base_stress = mask_intensity * 0.5

    # Neuroticism amplifies stress (sensitive avatars suffer more from lying)
    sensitivity = avatar.personality.neuroticism

    # Moral flexibility reduces stress (Machiavellian avatars lie easily)
    # If moral_flexibility is 1.0, they feel almost no stress.
    conscience_factor = 1.0 - avatar.moral_flexibility

    # Final formula
    # Stress = Mask * Sensitivity * Conscience
    # Example: High Mask (0.8) * High Neuroticism (0.8) * Low Flexibility (0.2 conscience) = 0.12 stress increase
    stress_increase = base_stress * (0.5 + sensitivity) * (0.2 + conscience_factor)

    # Clamp result
    min(stress_increase, 10.0)
  end

  @doc """
  Decides whether the avatar should use a mask in a given social interaction.
  Returns `{:ok, mask_intensity}` or `{:error, reason}`.

  ## Parameters
  - avatar: The acting avatar.
  - target_reputation: The reputation of the person they are talking to (0.0 to 1.0).
  - stakes: How important is this interaction? (0.0 to 1.0).
  """
  @spec decide_strategy(Avatar.t(), float(), float()) :: {:mask, float()} | :authentic
  def decide_strategy(%Avatar{} = avatar, target_reputation, stakes) do
    ambition = avatar.social_persona.social_ambition
    flexibility = avatar.moral_flexibility

    # 1. Calculate incentive to lie (Strategic Gain)
    # We lie if the stakes are high or the target is powerful (and we are ambitious)
    incentive = target_reputation * ambition + stakes

    # 2. Calculate resistance to lie (Integrity)
    # Resistance comes from low flexibility and high conscientiousness
    integrity = 1.0 - flexibility + avatar.personality.conscientiousness * 0.5

    # 3. Decision
    if incentive > integrity do
      # Calculate how thick the mask should be based on the gap
      intensity = min(incentive - integrity, 1.0)
      {:mask, intensity}
    else
      :authentic
    end
  end

  @doc """
  Updates the avatar's hypocrisy state after an interaction.
  """
  @spec process_interaction(Avatar.t(), float()) :: Avatar.t()
  def process_interaction(%Avatar{} = avatar, mask_used) do
    # Update current mask intensity moving average
    current = avatar.social_persona.current_mask_intensity
    new_intensity = current * 0.8 + mask_used * 0.2

    new_persona = %{avatar.social_persona | current_mask_intensity: new_intensity}
    %{avatar | social_persona: new_persona}
  end
end
