name: Bug Report
description: Report a bug in VIVA
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out as much as possible to help us.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Describe the bug clearly and concisely
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Start with 'iex -S mix'
        2. Run '...'
        3. See the error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of VIVA is affected?
      options:
        - viva_core (Emotional GenServer)
        - viva_core (Memory)
        - viva_bridge (Rust NIF)
        - viva_bridge (Body)
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: Ubuntu 22.04
        - Elixir: 1.17.0
        - Erlang/OTP: 27.0
        - Rust: 1.80.0
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Paste relevant logs or stack traces
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and found no duplicate
          required: true
        - label: I am using the latest version
          required: false
