name: Feature Request
description: Suggest a new feature for VIVA
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem would this feature solve?
      placeholder: |
        I'm frustrated when...
        It would be useful if VIVA could...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you imagine the solution?
      placeholder: |
        VIVA could have a function that...
        The interface would be...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions?
      placeholder: Other approaches I thought about...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of VIVA would be affected?
      options:
        - viva_core (Soul - GenServers)
        - viva_bridge (Body - Rust NIF)
        - Documentation
        - Tests
        - CI/CD
        - Other / Don't know
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How important is it to you?
      options:
        - Nice to have
        - Important
        - Critical for my use
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, links, references...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to implement this feature
          required: false
        - label: I am willing to help with testing
          required: false
