import Config

# Configure your database (TimescaleDB)
config :viva, Viva.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5432,
  database: "viva_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  types: Viva.Infrastructure.PostgrexTypes

# Redis configuration
config :viva, :redis, url: System.get_env("REDIS_URL", "redis://localhost:6379")

# Qdrant vector database
config :viva, :qdrant,
  url: System.get_env("QDRANT_URL", "http://localhost:6333"),
  api_key: System.get_env("QDRANT_API_KEY")

# NVIDIA NIM (local development)
config :viva, :nim,
  base_url: System.get_env("NIM_BASE_URL", "http://localhost:8000"),
  api_key: System.get_env("NIM_API_KEY"),
  timeout: 60_000

# Oban dev config - usando configuração normal para executar jobs
# config :viva, Oban, testing: :manual  # comentado para permitir execução real

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :viva, VivaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1BkVce2u2wQ0RVdqo4ZWSvEBXJ5AWse36iH5/SpdOs+6T1RqCyVyTjMy4CR+MzGo",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:viva, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:viva, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :viva, VivaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/viva_web/router\.ex$",
      ~r"lib/viva_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :viva, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Groq Cloud LLM Backend (ultra-fast ~700ms inference)
config :viva, Viva.AI.LLM.Backends.GroqBackend,
  api_key: System.get_env("GROQ_API_KEY"),
  model: "llama-3.3-70b-versatile",
  timeout: 30_000

# Gemini CLI Backend (fallback) - Auto Gemini 3
config :viva, Viva.AI.LLM.Backends.GeminiCliBackend,
  executable: "gemini",
  # model: nil = Auto (Gemini 3 Flash + Pro)
  timeout: 30_000

# LLM Router Strategy
config :viva, Viva.AI.LLM.Backends.Router,
  strategy: :local_first,  # :local_first | :cloud_first | :local_only | :cloud_only
  local_max_tokens: 500,
  fallback_on_error: true

# LLM Queue Settings
config :viva, Viva.AI.LLM.Backends.Queue,
  max_concurrent: 4,
  max_queue_size: 1000,
  default_timeout: 30_000

# LlmClient - use local LLM for avatar thoughts
config :viva, Viva.AI.LLM.LlmClient,
  use_local_for_thoughts: true
